/* Time Clocks Unlimited — catalog data (real products, models, specs & pricing from timeclocksunltd.com) */
const IMG = 'assets/products/';

/* Configurable option — NetBell PA "Number of Speakers" (from timeclocksunltd.com:
   base price includes 2 speakers; each additional speaker adds $394). */
const SPEAKER_OPTIONS = { label:'Number of Speakers', choices:[
  { label:'2 Speakers', add:0 },
  { label:'3 Speakers', add:394 },
  { label:'4 Speakers', add:788 },
  { label:'5 Speakers', add:1182 },
  { label:'6 Speakers', add:1576 }
]};

const CATEGORIES = [
  {
    id: 'netbell-pa', name: 'NetBell IP Public Address', short: 'IP Paging & PA Systems', nav: 'IP Paging',
    tagline: 'Mass communication over your existing network',
    blurb: 'Connect every speaker across multiple buildings with a single network cable. Daily announcements, scheduled break bells, fire drills and OSHA-compliant emergency alerts — all managed from a simple desktop app or web browser.',
    icon: 'speaker', color: '#2563eb',
    benefits: [
      { t: 'Reduced Wiring Costs', d: 'Leverage your existing network — minimize expensive cabling and labor.' },
      { t: 'Simple DIY Installation', d: 'Install it yourself with just a screwdriver. Set up in minutes, no contractors.' },
      { t: 'Scalable for Growth', d: 'Start small and add more speakers anytime — no rewiring the whole facility.' },
      { t: 'Web-Based Scheduler', d: 'Program bell schedules from any browser with custom tones and messages.' },
      { t: 'VoIP Compatible', d: 'Integrate with your VoIP phone system for unified facility communications.' },
      { t: 'Seamless Integration', d: 'Tie into fire/security systems via digital inputs or RESTful API for instant emergency messages.' }
    ]
  },
  {
    id: 'break-bells', name: 'Break Bells & Buzzers', short: 'School, Office & Factory', nav: 'Break Bells',
    tagline: 'Web & wired bell / buzzer systems',
    blurb: 'Set up a facility-wide break bell system in minutes. Choose network-enabled LINORTEK NetBell systems scheduled from any web browser, or classic wired timer-switch bell & buzzer assemblies — for schools, warehouses and factories.',
    icon: 'bell', color: '#f26a1b',
    subs: ['Web-Based / TCP-IP Systems', 'Wired Timer Switches']
  },
  {
    id: 'software', name: 'Time & Attendance', short: 'Biometric Clocks & Software', nav: 'Biometric Clocks',
    tagline: 'Facial recognition, fingerprint & cloud software',
    blurb: 'Touch-free facial-recognition and fingerprint terminals that stop "buddy punching" and flow straight into payroll. uAttend cloud clocks with mobile app & PTO tracking, and Qqest TimeForce 2 biometric systems trusted by 46,000+ businesses.',
    icon: 'face', color: '#0a1c2e',
    subs: ['uAttend Software', 'Qqest Software'],
    /* uAttend cloud-plan pricing band (content & signup link from timeclocksunltd.com uAttend page —
       the did= parameter is the dealer ID and must be preserved exactly) */
    pricingBand: {
      after: 'uAttend Software',
      eyebrow: 'uAttend Cloud Plans',
      title: 'Software Pricing',
      unit: 'employees', /* tier ranges are employee counts (confirmed by owner) */
      note: 'All clocks require a monthly subscription — the clocks will not work without one. All monthly cloud account plans are designed for two time clocks, one administrator, and unlimited data exports in .csv format. Add $12/month for each additional time clock over two. Add $8/month for each additional administrator over one. Add $8/month for data exports in formats other than .csv. Plus tax where applicable. Text alerts optional, with plans starting at $9.95 for up to 1,000 texts.',
      tiers: [
        { range:'1–9',   price:29 },
        { range:'10–19', price:49 },
        { range:'20–49', price:89 },
        { range:'50–99', price:149 },
        { range:'100+',  price:199 }
      ],
      cta: { label:'Sign Up for Your uAttend Account', url:'https://app1.trackmytime.com/signup/signup.aspx?did=dc7d9&new=0' },
      callNote: 'When you\'re ready to order your clock, call us and we\'ll help you place the order.'
    }
  },
  {
    id: 'time-clocks', name: 'Time Clocks', short: 'Amano Punch & Electronic', nav: 'Amano Clocks',
    tagline: 'Proven Amano time recorders',
    blurb: 'Reliable Amano electronic and punch-card time recorders — the workhorses of timekeeping. Authorized dealer; we service what we sell.',
    icon: 'clock', color: '#0891b2',
    subs: ['Amano Time Clocks']
  },
  {
    id: 'date-stamps', name: 'Date & Numbering Stamps', short: 'Widmer Stamps', nav: 'Date Stamps',
    tagline: 'Authorized Widmer dealer',
    blurb: 'A complete line of Widmer date stamps, time stamps, check signers and embossers for document control in mailrooms, banks and validation centers. We service what we sell — call us for any model.',
    icon: 'stamp', color: '#7c3aed',
    subs: ['Widmer Date Stamps']
  },
  {
    id: 'ribbons', name: 'Ribbons, Cards & Supplies', short: 'Genuine Supplies', nav: 'Supplies',
    tagline: 'Keep your clocks running clean',
    blurb: 'Genuine replacement ribbons and time cards engineered for sharp, smudge-free imprints. Check the compatibility list on each item to match your exact clock model.',
    icon: 'supplies', color: '#16a34a'
  },
  {
    id: 'wireless', name: 'Wireless Break Systems', short: 'Wireless Bells & Paging', nav: 'Wireless',
    tagline: 'Cordless break bells, pagers & horn speakers',
    blurb: 'Durable, compact wireless break-bell and paging systems with backup battery — add a speaker anywhere without running wire. Indoor and outdoor units work as pagers, bells, sirens, strobe lights and horn speakers, operating off relay antenna signals.',
    icon: 'speaker', color: '#0d9488', empty: true
  }
];

/* product fields: id (=image basename), cat, sub, name, model, img, price, list, brand, short, bullets[], specs{}, compat[], desc */
const PRODUCTS = [
  /* ---------- NetBell IP Public Address ---------- */
  { id:'01-910-00057', cat:'netbell-pa', name:'NetBell Warehouse / Factory Paging System', model:'Facility-wide IP paging & break-time system', img:IMG+'01-910-00057-1.jpg', price:2566, list:null, brand:'Linortek',
    options:SPEAKER_OPTIONS,
    short:'Everything needed for factory/warehouse mass notification — live announcements, pre-recorded messages, fire drills and break-bell scheduling.',
    bullets:['Web-based control of up to 500 programmable events','Extra-loud hardware cuts through industrial noise','Plug-and-play on your existing network, mounting hardware included','Custom or recorded tones; NTP automatic time sync'],
    desc:'Streamline daily operations across large floor plans. This all-in-one IP paging system automates every work bell and break buzzer with synchronized audio cues for lunch and shift changes — ideal for manufacturing plants, distribution centers, bakeries and textile mills.' },
  { id:'01-910-00058', cat:'netbell-pa', name:'School IP Paging Bell System', model:'Campus-wide bells, paging & emergency alerts', img:IMG+'01-910-00058-1.jpg', price:2566, list:null, brand:'Linortek',
    options:SPEAKER_OPTIONS,
    short:'Connect every speaker through your existing network — automated bell scheduling, campus-wide paging and emergency alerts for schools of any size.',
    bullets:['No expensive contractors or new wiring','Automated class-change & assembly bells','Live and pre-recorded campus announcements','Simple to install, affordable to own'],
    desc:'Transform your school’s communication with a complete IP audio solution: daily bells, all-call paging and critical emergency announcements, all from one web interface.' },
  { id:'01-910-00146', cat:'netbell-pa', name:'Warehouse & Factory Paging with VoIP', model:'VoIP phone integration + automated bells', img:IMG+'01-910-00146-1.jpg', price:2890, list:null, brand:'Linortek',
    options:SPEAKER_OPTIONS,
    short:'Make announcements directly from any desk phone while automating daily break bells, shift changes and emergency alerts.',
    bullets:['VoIP phone-system integration','Live paging from any handset','Automated break & shift signaling','Emergency notification ready'],
    desc:'Professional industrial communication with VoIP integration — perfect for facilities that want one simple system for mass communication and emergency notification.' },
  { id:'01-910-00137', cat:'netbell-pa', name:'NetBell Emergency Alert & Safety Paging', model:'OSHA-compliant emergency notification', img:IMG+'01-910-00137-1.jpg', price:3051, list:null, brand:'Linortek',
    options:SPEAKER_OPTIONS,
    short:'IP-based emergency system with instant alerts, pre-recorded messages, live announcements and one-button activation — 10,000 sq ft coverage per speaker.',
    bullets:['One-button instant emergency activation','Real-time voice, pre-recorded or automated triggers','10,000 sq ft coverage per speaker','OSHA-compliant employee alarm; deploys in hours'],
    desc:'Deliver critical information through live voice, pre-recorded messages or automated triggers from connected systems — built for manufacturing facilities, distribution centers and industrial complexes requiring immediate emergency communication.' },

  /* ---------- Break Bells & Buzzers — Web-Based / TCP-IP (Linortek) ---------- */
  { id:'01-910-00014', cat:'break-bells', sub:'Web-Based / TCP-IP Systems', name:'NetBell-2 TCP/IP Web-Based Bell Controller', model:'Controller only — up to 500 event schedules', img:IMG+'01-910-00014-1.jpg', price:425, list:468, brand:'Linortek',
    short:'The network "brains" of a school/factory bell system. Add your own bells or buzzers; schedule up to 500 events from any browser.',
    bullets:['Up to 500 programmable event schedules','No dedicated PC or extra software required','Schedule from any computer on your network'],
    desc:'A compact, self-contained network bell controller. Connect it to your existing bells or buzzers and program your entire schedule from a simple web browser.' },
  { id:'01-910-00025', cat:'break-bells', sub:'Web-Based / TCP-IP Systems', name:'NetBell-2 with 1 Bell', model:'Netbell-2-1Bel — controller + one 6" alarm bell', img:IMG+'01-910-00025-1.jpg', price:699, list:763, brand:'Linortek',
    short:'All-in-one kit: the versatile NetBell-2 controller plus a high-quality 6" work bell — a fully operational break-bell system out of the box.',
    bullets:['Up to 500 programmable events, each its own duration','No extra software or designated computer','Add a 2nd bell or a buzzer later as you grow','Manage break & shift times from any PC'],
    desc:'One of our most popular break-time solutions. Best for small-to-medium workshops, schools and warehouses needing a reliable, network-controlled schedule — with the future-proof benefit of expanding to a second device on the same controller.',
    specs:{ 'Event schedules':'Up to 500', 'Bell':'6" alarm bell included', 'Control':'Web browser, any networked PC', 'Expandable':'Add 2nd bell / buzzer' } },
  { id:'01-910-00027', cat:'break-bells', sub:'Web-Based / TCP-IP Systems', name:'NetBell-2 with 2 Bells', model:'Netbell-2-2Bel — controller + two 6" bells', img:IMG+'01-910-00027-1.jpg', price:985, list:1058, brand:'Linortek',
    short:'The web-based NetBell-2 controller with two loud 6" signal bells — perfect for noisier environments where audible alerts are critical.',
    bullets:['Two high-quality signal bells included','Schedule shift changes, breaks or class periods from a browser','Scale up by adding more bells or speakers','Functions as part of a modern IP PA system'],
    desc:'Connects to your existing network and delivers complete control from a web browser — no special software to install. Ideal for larger or louder facilities.' },
  { id:'01-910-00026', cat:'break-bells', sub:'Web-Based / TCP-IP Systems', name:'NetBell-2-1Buzzer Network Buzzer System', model:'Netbell-2-1PBuz — one 4" extra-loud buzzer', img:IMG+'01-910-00026-1.jpg', price:780, list:873, brand:'Linortek',
    short:'Network bell controller with one 4" extra-loud buzzer for industrial factory & warehouse break-time alerts.',
    bullets:['One 4" extra-loud industrial buzzer','Web-based scheduling software','Works with your existing time-clock software & network'],
    desc:'An Ethernet-enabled buzzer system that eliminates manual oversight — accurate signaling for shifts, meetings and emergencies, managed from any computer on your network.' },
  { id:'01-910-00028', cat:'break-bells', sub:'Web-Based / TCP-IP Systems', name:'NetBell-2-2Buzzer Network Buzzer System', model:'Netbell-2-2Buzzer — two 4" extra-loud buzzers', img:IMG+'01-910-00028-1.jpg', price:1140, list:1278, brand:'Linortek',
    short:'Two 4" extra-loud buzzers on one web-managed controller for maximum coverage in noisy industrial spaces.',
    bullets:['Two loud, high-quality buzzers included','Simple web interface, no PC software','Integrates with existing infrastructure'],
    desc:'Dependable, consistent scheduling for shifts, meetings and emergencies — built for large factory and warehouse floor plans.' },
  { id:'01-910-00119', cat:'break-bells', sub:'Web-Based / TCP-IP Systems', name:'NetBell-4-4Buz Network Buzzer System', model:'Four built-in buzzers + four contact closures', img:IMG+'01-910-00119-1.jpg', price:2089, list:2332, brand:'Linortek',
    short:'Run four distinct schedules from one device — used by large school districts, hospitals and expansive factories.',
    bullets:['Four independent zones / schedules','Automatic NTP time synchronization','Power of four devices in one compact enclosure','No complex internal wiring'],
    desc:'An advanced programmable bell system for multi-zone environments that demand strict time adherence — synchronized break-time signaling across departments or buildings.' },
  { id:'01-910-00035', cat:'break-bells', sub:'Web-Based / TCP-IP Systems', name:'NETBELL-4K Bell Controller Kit', model:'NEMA-rated, four relay outputs', img:IMG+'01-910-00035-1.jpg', price:641, list:712, brand:'Linortek',
    short:'Industrial NEMA-rated controller with four relay outputs to independently control up to four bells or signaling devices.',
    bullets:['Four relay outputs — up to four devices/zones','Up to 500 unique event schedules','Digital input for manual emergency ringing','Manage multiple units from a single interface'],
    desc:'Housed in a durable NEMA-rated enclosure for factories and warehouses. One of the most flexible break-time solutions available — program every zone from a browser with no software to install.' },
  { id:'01-910-00072', cat:'break-bells', sub:'Web-Based / TCP-IP Systems', name:'NetBell-KB Network Break Buzzer (Two-Zone)', model:'Netbell-KB-E2M — dual extra-loud outputs', img:IMG+'01-910-00072-1.jpg', price:1475, list:1553, brand:'Linortek',
    short:'Two-zone automated alerting for areas needing sharp, extra-loud signals — e.g. a warehouse floor and an assembly line.',
    bullets:['Dual outputs for two physically-separated zones','Automatic NTP time sync','Stagger lunches or shift changes by zone','Managed entirely via web interface'],
    desc:'A centralized break-bell system for industrial settings requiring high-decibel signals heard across different operational sections — unparalleled flexibility coordinating facility-wide timing.' },
  { id:'_01-910-00005', cat:'break-bells', sub:'Web-Based / TCP-IP Systems', name:'NetBell-K-C Break Bell & Clock System', model:'All-in-one bell + synchronized digital clock', img:IMG+'_01-910-00005-1.jpg', price:1250, list:1339, brand:'Linortek',
    short:'Network-based bell system with an included digital clock for a clear, unified time reference across your whole team.',
    bullets:['Up to 500 programmable event schedules','Built-in real-time clock, NTP + automatic DST/leap-year','BellScheduler desk app manages devices in multiple buildings','No wiring or control systems needed'],
    desc:'Completely automates time-based alerts for manufacturing plants, warehouses, distribution centers and schools. The included digital clock keeps everyone on the same page; manage multiple NetBell devices from one interface without going through the firewall.',
    specs:{ 'Event schedules':'Up to 500', 'Clock':'Built-in, NTP + auto DST', 'App':'BellScheduler desk app', 'Multi-building':'Yes' } },
  { id:'01-910-00059', cat:'break-bells', sub:'Web-Based / TCP-IP Systems', name:'NetBell-NTG Tone & Message Generator', model:'For schools / commercial PA systems', img:IMG+'01-910-00059-1.jpg', price:748, list:831, brand:'Linortek',
    short:'Turns your existing speakers into a web-based programmable bell system — generates digital tones and pre-recorded voice messages instead of physical bells.',
    bullets:['40 standard tones/messages; record custom up to 120 hrs','16 tones selectable by schedule or digital input','Plays over your current PA / paging speakers','BellScheduler app for easy management'],
    desc:'An all-in-one upgrade if you already have speakers installed. Bridges a basic break-bell system and a full IP public address system — schedule different tones for different events or play voice messages for security alerts and shift changes.' },
  { id:'01-910-00075', cat:'break-bells', sub:'Web-Based / TCP-IP Systems', name:'NetBell-NTG-C2 Paging System (2 Speakers)', model:'TCP/IP PA paging with live voice', img:IMG+'01-910-00075-1.jpg', price:1882, list:2091, brand:'Linortek',
    short:'Complete two-speaker IP public address system handling both scheduled alerts and live voice paging.',
    bullets:['Two high-quality speakers included','Integrated microphone input for live announcements','Schedule tones, messages or background music','NTP automatic time synchronization'],
    desc:'Combines a break-bell system with full paging capabilities — broadcast custom tones, messages and music, or make immediate live emergency announcements over excellent dual-speaker coverage.' },
  { id:'01-910-00013', cat:'break-bells', sub:'Web-Based / TCP-IP Systems', name:'NetBell-K TCP/IP Break Bell System', model:'Web-based all-in-one, up to 500 events', img:IMG+'01-910-00013-1.jpg', price:755, list:839, brand:'Linortek',
    short:'A self-contained, web-based all-in-one school/factory break-bell system with up to 500 event schedules.',
    bullets:['Up to 500 event schedules','All-in-one, self-contained','Web-based management'],
    desc:'A dependable, network-controlled break-bell system that runs independently of your main computer for superior reliability.' },
  { id:'01-910-00045', cat:'break-bells', sub:'Web-Based / TCP-IP Systems', name:'NetBell-K-E1 Web-Based Break Bell System', model:'All-in-one with one external bell', img:IMG+'01-910-00045-1.jpg', price:1050, list:1154, brand:'Linortek',
    short:'Loud all-in-one electric school/factory/warehouse break-alarm system with one external bell and programmable web-based timer software.',
    bullets:['One external bell included','Programmable web-based bell timer','Self-contained electronic controller'],
    desc:'A loud, automatic, programmable break-bell system for schools, factories and warehouses — web-based control with no PC software to install.' },
  { id:'01-910-00049', cat:'break-bells', sub:'Web-Based / TCP-IP Systems', name:'NetBell-K-E2M Web-Based Break Bell System', model:'Two external bells + manual push-button', img:IMG+'01-910-00049-1.jpg', price:1350, list:1498, brand:'Linortek',
    short:'All-in-one loud break-bell system with two external bells and a push-button switch to ring the bell manually for emergencies.',
    bullets:['Two external bells included','Manual push-button for emergency ring','Programmable web-based timer software'],
    desc:'A loud, automatic, programmable break-bell system with two bells for wider coverage plus a manual override for emergencies.' },
  { id:'01-910-00029', cat:'break-bells', sub:'Web-Based / TCP-IP Systems', name:'NETBELL-KL High-Volume Break Bell System', model:'90 dBA @ 30 ft for noisy/large areas', img:IMG+'01-910-00029-1.jpg', price:910, list:1011, brand:'Linortek',
    short:'Self-contained web-based break-bell system with a high-volume 90 dBA @ 30′ bell for noisier, larger industrial working areas.',
    bullets:['High-output 90 dBA @ 30′ bell','Fully automated programmable schedule','No extra software; runs independently of your PC','Instant schedule changes from any networked computer'],
    desc:'Engineered for large, noisy industrial spaces — an incredibly loud bell guaranteed to cut through industrial noise, in a self-contained, maintenance-free design built for harsh environments.' },

  /* ---------- Break Bells & Buzzers — Wired Timer Switches ---------- */
  { id:'AP21LV', cat:'break-bells', sub:'Wired Timer Switches', name:'AP21LV Timer Switch', model:'Programmable wired bell/buzzer timer', img:IMG+'AP21LV-1.jpg', price:240, list:null, brand:'Wired System',
    short:'Programmable wired timer switch to drive a bell or buzzer on a daily or per-day-of-week schedule.',
    bullets:['Easily programmable schedules','Daily or per-weekday timing','Drives a bell or buzzer'] },
  { id:'AP21-BP1', cat:'break-bells', sub:'Wired Timer Switches', name:'AP21-BP1 Break Bell System', model:'Complete wired break-bell system', img:IMG+'AP21-BP1-1.jpg', price:485, list:null, brand:'Wired System',
    short:'Complete wired break-bell system with a pleasant-tone bell — reliable and easily schedulable.',
    bullets:['Pleasant-tone bell included','Reliable, durable assembly','Easily programmable'] },
  { id:'MC41LV', cat:'break-bells', sub:'Wired Timer Switches', name:'MC41LV Timer Switch', model:'Advanced multi-schedule wired timer', img:IMG+'MC41LV-1.jpg', price:499, list:null, brand:'Wired System',
    short:'Advanced wired programmable timer switch for multi-schedule bell/buzzer control.',
    bullets:['Multiple programmable schedules','Drives bell or buzzer','Durable, reliable'] },
  { id:'MC41-BP1', cat:'break-bells', sub:'Wired Timer Switches', name:'MC41-BP1 Break Bell System', model:'Wired break-bell on MC41 timer', img:IMG+'MC41-BP1-1.jpg', price:580, list:null, brand:'Wired System',
    short:'Wired break-bell system built on the advanced MC41 programmable timer.',
    bullets:['MC41 programmable timer','Pleasant-tone bell','Flexible scheduling'] },
  { id:'AP21-BH1-TXO', cat:'break-bells', sub:'Wired Timer Switches', name:'AP21-BH1 Break Buzzer System (TXO)', model:'Wired buzzer system w/ TXO chip', img:IMG+'AP21-BH1-TXO-1.jpg', price:645, list:null, brand:'Wired System',
    short:'Wired break-buzzer system with TXO chip for reliable scheduled alerts.',
    bullets:['TXO chip for reliability','Loud break buzzer','Programmable schedule'] },
  { id:'AP21-BH2-TXO', cat:'break-bells', sub:'Wired Timer Switches', name:'AP21-BH2 Extra-Loud Break Buzzer System', model:'Extra buzzer + heavy-duty supply, 100 dB @ 10 ft', img:IMG+'AP21-BH2-TXO-1.jpg', price:895, list:null, brand:'Wired System',
    short:'Extra-loud buzzer system (100 dB @ 10 ft) with an extra buzzer and heavy-duty power supply, TXO chip.',
    bullets:['100 dB @ 10 ft — extra loud','Includes extra buzzer','Heavy-duty power supply','TXO chip'],
    specs:{ 'Loudness':'100 dB @ 10 ft', 'Buzzers':'2', 'Power':'Heavy-duty supply' } },
  { id:'MC41-BH1', cat:'break-bells', sub:'Wired Timer Switches', name:'MC41-BH1 Break Buzzer System', model:'Wired buzzer on MC41 timer', img:IMG+'MC41-BH1-1.jpg', price:875, list:null, brand:'Wired System',
    short:'Wired break-buzzer system on the advanced MC41 programmable timer.',
    bullets:['MC41 programmable timer','Loud break buzzer','Flexible multi-schedule'] },
  { id:'MC4181NX', cat:'break-bells', sub:'Wired Timer Switches', name:'MC4181NX Master Clock', model:'Wired master clock for facility sync', img:IMG+'MC4181NX-1.jpg', price:1100, list:1200, brand:'Wired System',
    short:'Wired master clock to synchronize bells, buzzers and clocks across your facility.',
    bullets:['Synchronizes facility-wide signaling','Reliable master time source','Drives multiple zones'] },
  { id:'F-4436PB1', cat:'break-bells', sub:'Wired Timer Switches', name:'F-4436PB1 Push-Button Bell System', model:'Manual push-button bell', img:IMG+'F-4436PB1-1.jpg', price:370, list:null, brand:'Wired System',
    short:'Manual push-button bell system for on-demand ringing.',
    bullets:['Push-button on-demand ring','Simple, reliable','Durable assembly'] },
  { id:'F350PB1', cat:'break-bells', sub:'Wired Timer Switches', name:'Push-Button Buzzer System', model:'Manual push-button buzzer', img:IMG+'F350PB1-1.jpg', price:435, list:null, brand:'Wired System',
    short:'Manual push-button buzzer system for on-demand industrial alerts.',
    bullets:['Push-button on-demand buzzer','Loud industrial tone','Simple operation'] },
  { id:'F-TG4X', cat:'break-bells', sub:'Wired Timer Switches', name:'Tone Generator', model:'Tone generator for wired signaling', img:IMG+'F-TG4X-1.jpg', price:225, list:null, brand:'Wired System',
    short:'Tone generator for wired bell/buzzer signaling systems.',
    bullets:['Generates signaling tones','Pairs with wired systems','Reliable'] },
  { id:'MC22-BH1', cat:'break-bells', sub:'Wired Timer Switches', name:'MC22-BH1 Break Buzzer System', model:'Wired buzzer system', img:IMG+'MC22-BH1-1.jpg', price:845, list:null, brand:'Wired System',
    short:'Wired MC22-series break-buzzer system for scheduled industrial alerts.',
    bullets:['Programmable schedule','Loud break buzzer','Durable assembly'] },
  { id:'MC22-BH2', cat:'break-bells', sub:'Wired Timer Switches', name:'MC22-BH2 Break Buzzer System', model:'Wired dual-buzzer system', img:IMG+'MC22-BH2-1.jpg', price:1070, list:null, brand:'Wired System',
    short:'Wired MC22-series break-buzzer system with extra buzzer for wider coverage.',
    bullets:['Two buzzers for wider coverage','Programmable schedule','Durable assembly'] },
  { id:'F-350-24A1', cat:'break-bells', sub:'Wired Timer Switches', name:'F-350-24A1 Extra Break Buzzer', model:'Add-on extra buzzer', img:IMG+'F-350-24A1-1.jpg', price:318, list:null, brand:'Wired System',
    short:'Add-on extra buzzer to extend coverage of your wired break system.',
    bullets:['Extends coverage','Matches wired systems','Loud industrial tone'] },
  { id:'Heavy-Duty-Power-Supply', cat:'break-bells', sub:'Wired Timer Switches', name:'Heavy-Duty Power Supply', model:'Replacement / upgrade power supply', img:IMG+'Heavy-Duty-Power-Supply-1.jpg', price:75, list:null, brand:'Accessory',
    short:'Heavy-duty power supply for wired bell and buzzer systems.',
    bullets:['Heavy-duty rated','For wired bell/buzzer systems'] },
  { id:'8901-1411-R', cat:'break-bells', sub:'Wired Timer Switches', name:'Relay / Transformer Assembly', model:'Replacement relay/transformer', img:IMG+'8901-1411-R-1.jpg', price:225, list:null, brand:'Accessory',
    short:'Replacement relay / transformer assembly for wired break systems.',
    bullets:['Relay + transformer','Replacement / spare part'] },
  { id:'1109', cat:'break-bells', sub:'Wired Timer Switches', name:'Key Lock Box', model:'Locking enclosure', img:IMG+'1109-1.jpg', price:138, list:null, brand:'Accessory',
    short:'Key lock box to secure your wired timer/controller from tampering.',
    bullets:['Locking enclosure','Tamper protection'] },
  { id:'F-4436-24A1', cat:'break-bells', sub:'Wired Timer Switches', name:'Extra Bell Assemblies', model:'Add-on bell assembly', img:IMG+'F-4436-24A1-1.jpg', price:225, list:null, brand:'Accessory',
    short:'Extra bell assembly to add coverage to your wired break-bell system.',
    bullets:['Add-on bell','Extends coverage'] },

  /* ---------- Time & Attendance — uAttend (cloud biometric clocks) ---------- */
  { id:'JR2000', cat:'software', sub:'uAttend Software', name:'uAttend JR2000 Time Clock', model:'Touch tablet with biometric finger scanner', img:IMG+'JR2000-1.png', price:179, list:null, brand:'uAttend',
    short:'Affordable touch-tablet cloud time clock with a biometric fingerprint scanner and RFID reader — Wi-Fi or LAN, free lifetime support, no contracts.',
    bullets:['Biometric fingerprint + RFID badge','Wi-Fi / LAN connectivity','Cloud dashboard, reports & payroll export','Requires uAttend monthly plan (from $29/mo)'],
    desc:'uAttend’s affordable, cloud-connected time & attendance system features easy setup and free lifetime support. Track missed punches and who’s in, run dozens of reports, and export hours to any payroll system in seconds. (All uAttend clocks require a monthly cloud subscription.)' },
  { id:'DR2000', cat:'software', sub:'uAttend Software', name:'uAttend DR2000 Time Clock', model:'Touch-free voice control & facial recognition', img:IMG+'DR2000-1.jpg', price:299, list:null, brand:'uAttend',
    short:'Touch-free facial recognition (even with masks) plus voice control — eliminates "buddy punching" and keeps surfaces hygienic.',
    bullets:['Facial recognition, voice, RFID badge & PIN','Recognizes faces even with masks on','Offline mode stores punches during outages','Dedicated mobile app; cloud software, payroll export'],
    desc:'A cutting-edge, cloud-based terminal for the best workforce management. View time cards, track PTO accruals and export directly to major payroll systems — secure, touch-free and uninterrupted timekeeping. (Requires uAttend monthly plan.)',
    specs:{ 'Punch methods':'Face, voice, RFID, PIN', 'Masks':'Recognized', 'Connectivity':'Wi-Fi / LAN', 'Offline':'Yes, stores punches', 'App':'Mobile app included' } },
  { id:'DR2500', cat:'software', sub:'uAttend Software', name:'uAttend DR2500 Time Clock', model:'Facial recognition + temperature reader', img:IMG+'DR2500-1.jpg', price:399, list:null, brand:'uAttend',
    short:'All the DR2000 touch-free facial & voice recognition, plus an integrated temperature reader for added workplace safety.',
    bullets:['Touch-free facial & voice recognition','Integrated temperature reading','Wi-Fi / LAN real-time data','Cloud software & mobile app'],
    desc:'Adds advanced facial recognition and temperature screening — automating the most error-prone part of timekeeping: the punch itself. Functions standalone or as a front-end to your existing system. (Requires uAttend monthly plan.)' },

  /* ---------- Time & Attendance — Qqest (TimeForce 2 / Velocity) ---------- */
  { id:'V800', cat:'software', sub:'Qqest Software', name:'Velocity 800 Time Clock', model:'Fingerprint & on-demand technology', img:IMG+'V800-1.jpg', price:1290, list:null, brand:'Qqest',
    short:'Professional fingerprint time clock with on-demand technology, running on Qqest TimeForce 2 — trusted by 46,000+ businesses.',
    bullets:['Biometric fingerprint','On-demand technology','Runs on Qqest TimeForce 2 software'],
    desc:'A robust fingerprint terminal from the Velocity line on Qqest’s elite TimeForce 2 platform — 20+ years of industry leadership for reliable daily punching across your workforce.' },
  { id:'V850', cat:'software', sub:'Qqest Software', name:'Velocity 850 Time Clock', model:'Fingerprint + Dept Transfer, Job Costing, Tips', img:IMG+'V850-1.jpg', price:1790, list:null, brand:'Qqest',
    short:'Velocity 850 adds department transfer, job costing and tips keys — ideal for businesses that bill by job or track tipped labor.',
    bullets:['Fingerprint + on-demand technology','Department transfer & job costing','Tips keys for hospitality','Qqest TimeForce 2 software'],
    desc:'A feature-rich biometric terminal for operations that allocate labor to departments or jobs and capture tips at the clock.' },
  { id:'V850R', cat:'software', sub:'Qqest Software', name:'Velocity 850 Rugged', model:'Worksite-ready: Ethernet, POE or Wireless', img:IMG+'V850R-1.jpg', price:2290, list:null, brand:'Qqest',
    short:'A ruggedized Velocity 850 designed for worksites, with three connectivity options — Ethernet, POE or Wireless.',
    bullets:['Rugged housing for job sites','Dept transfer, job costing, tips keys','Three options: Ethernet, POE, Wireless','Qqest TimeForce 2 software'],
    desc:'Built to take on demanding worksites while keeping all the job-costing power of the Velocity 850 — choose the connectivity that fits your environment.' },

  /* ---------- Time Clocks — Amano ---------- */
  { id:'CP-5000', cat:'time-clocks', sub:'Amano Time Clocks', name:'Amano CP-5000 Electronic Time Recorder', model:'Electronic time recorder', img:IMG+'CP-5000-1.jpg', price:950, list:1150, brand:'Amano',
    short:'A dependable Amano electronic time recorder for straightforward, accurate punch-card timekeeping.',
    bullets:['Amano reliability','Electronic time recording','Authorized dealer — we service what we sell'],
    desc:'A proven Amano workhorse for businesses that want simple, accurate, low-maintenance time recording.' },
  { id:'MJR-PLUS', cat:'time-clocks', sub:'Amano Time Clocks', name:'Amano MJR-PLUS', model:'Calculating time recorder', img:IMG+'MJR-PLUS-1.jpg', price:499, list:null, brand:'Amano',
    short:'Affordable Amano MJR-series calculating time recorder for small and growing teams.',
    bullets:['Amano MJR series','Calculating time recorder','Great value'],
    desc:'An economical entry into Amano’s trusted MJR line — reliable punch-card timekeeping that totals hours for you.' },
  { id:'MJR-7000-1167', cat:'time-clocks', sub:'Amano Time Clocks', name:'Amano MJR-7000', model:'Calculating time recorder', img:IMG+'MJR-7000-1167-1.png', price:1250, list:1475, brand:'Amano',
    short:'The popular Amano MJR-7000 calculating time recorder — accurate totals and dependable daily operation.',
    bullets:['Amano MJR-7000','Automatic hour calculation','Uses MJR 0-99 time cards & black ribbon'],
    desc:'A higher-capacity Amano calculating recorder for busier workplaces — pair it with MJR time cards and ribbons (in our Supplies category).' },
  { id:'PIX-200-0400', cat:'time-clocks', sub:'Amano Time Clocks', name:'Amano PIX-200 Time Clock / Date Stamp', model:'Electronic time clock & date stamp', img:IMG+'PIX-200-0400-1.jpg', price:395, list:455, brand:'Amano',
    short:'Versatile Amano PIX-200 that works as both an electronic time clock and a document date stamp.',
    bullets:['Dual purpose: time clock + date stamp','Uses C3000 time cards & PIX10 ribbons','Compact and reliable'],
    desc:'A flexible Amano unit for offices that need both employee timekeeping and document time/date stamping in one device.' },
  { id:'PIX200-with-signal-kit', cat:'time-clocks', sub:'Amano Time Clocks', name:'Amano PIX-200 with Timer Signal Kit', model:'PIX-200 bundled with bell/signal kit', img:IMG+'PIX200-with-signal-kit-1.jpg', price:499, list:null, brand:'Amano',
    short:'The PIX-200 time clock / date stamp bundled with a timer signal kit to ring a bell or buzzer on schedule.',
    bullets:['PIX-200 time clock + date stamp','Includes timer signal kit','Drives a bell/buzzer on schedule'],
    desc:'Adds simple scheduled-signal capability to the dependable PIX-200 — a tidy combo for shops that want timekeeping and a break bell from one device.' },

  /* ---------- Date & Numbering Stamps — Widmer ---------- */
  { id:'T3', cat:'date-stamps', sub:'Widmer Date Stamps', name:'Widmer T-3 Electronic Date & Time Stamp', model:'Widmer T3 electronic time stamp', img:IMG+'T3-1.jpg', price:960, list:null, brand:'Widmer',
    short:'Precision Widmer T-3 electronic date & time stamp for clean, indisputable document time-stamping.',
    bullets:['Electronic date & time imprint','Authorized Widmer dealer','We service what we sell'],
    desc:'A reliable workhorse for mailrooms and offices that need accurate, legible date/time validation on documents.' },
  { id:'T3-LED', cat:'date-stamps', sub:'Widmer Date Stamps', name:'Widmer T3-LED Electronic Time Stamp', model:'T-3 with LED display', img:IMG+'T3-LED-1.jpg', price:1010, list:null, brand:'Widmer',
    short:'The Widmer T-3 with a clear LED display for easy reading and confident document stamping.',
    bullets:['Bright LED display','Electronic time stamp','Authorized Widmer dealer'],
    desc:'All the accuracy of the Widmer T-3 line with an added LED display for fast, error-free operation.' },
  { id:'776', cat:'date-stamps', sub:'Widmer Date Stamps', name:'Widmer 776 Dual-Head Date Stamp', model:'Stamps top & bottom of a document simultaneously', img:IMG+'776-1.jpg', price:1321, list:null, brand:'Widmer',
    short:'Heavy-duty dual-head date stamp for high-volume document validation — imprints the top and bottom of a document at once.',
    bullets:['Dual-head: stamps two locations simultaneously','Industrial-grade, high-volume','Ideal for mailrooms, banks, validation centers'],
    desc:'For high-volume environments needing instant, indisputable proof of time and date — processing checks, parking stubs and legal forms. One of the most important accessories for organizations validating paper records.' },

  /* ---------- Ribbons, Cards & Supplies ---------- */
  { id:'MJR-Ribbon', cat:'ribbons', name:'MJR Black Ribbon (Pack of 2)', model:'Single-color black ribbon', img:IMG+'MJR-Ribbon-1.jpg', price:48, list:null, brand:'Amano',
    short:'Genuine black ribbon, sold in a pack of 2.', bullets:['Pack of 2','Sharp, smudge-free imprints'],
    compat:['MJR-7000','MJR-8000'],
    desc:'Keep your Amano MJR recorder printing crisply. Stocking spares prevents payroll downtime and keeps timestamps legible for audits.' },
  { id:'PIX10', cat:'ribbons', name:'PIX10 Black Ribbons (Pack of 3)', model:'Black ribbon cartridges', img:IMG+'PIX10-1.jpg', price:54, list:null, brand:'Amano',
    short:'Black ribbon cartridges, sold in a pack of 3.', bullets:['Pack of 3','Premium nylon, resists drying'],
    compat:['TCX series: 11/21/22/45/85/90','PIX series: 10/15/21/25/55/75/95/200/3000x','BX-6000'],
    desc:'Wide-compatibility ribbon for many TCX and PIX series clocks — fresh ink ensures legible punches and protects you during labor-law audits.' },
  { id:'AR175', cat:'ribbons', name:'175 Black Ribbon (Pack of 3)', model:'AR175 black ribbon', img:IMG+'AR175-1.jpg', price:54, list:null, brand:'Acroprint',
    short:'Premium replacement cartridge for sharp, smudge-free imprints, pack of 3.', bullets:['Pack of 3','Durable nylon construction'],
    compat:['MRX-35','Acroprint 175','MP550 Date Stamp','ES700 / ES900','and many more'],
    desc:'A premium black ribbon engineered for legible imprints on every time card — durable nylon that resists drying out in high-traffic industrial environments.' },
  { id:'5650-Purple', cat:'ribbons', name:'5650 Purple Ribbons (Box of 6)', model:'Purple date-stamp ribbon', img:IMG+'5650-Purple-1.jpg', price:75, list:null, brand:'Amano',
    short:'Genuine purple ribbons for date-stamp machines, box of 6.', bullets:['Box of 6','Consistent, dark purple saturation'],
    compat:['5650 time clock'],
    desc:'Keep mechanical time clocks running smoothly with crisp, legible purple punches — a low-cost way to prevent payroll errors from faded cards.' },
  { id:'C3000', cat:'ribbons', name:'C3000 Time Cards (Box of 1000)', model:'Time cards, 1000 per box', img:IMG+'C3000-1.jpg', price:75, list:null, brand:'Amano',
    short:'Genuine C3000 time cards, 1000 per box.', bullets:['1000 cards per box','Smudge-resistant, durable stock'],
    compat:['PIX-200'],
    desc:'A perfect fit for the PIX-200 — sturdy cards engineered to prevent smudging and resist wear for confident, accurate records.' },
  { id:'MRX35-50-X-10', cat:'ribbons', name:'MRX-35 Time Cards (50-pack, 10 packs/box)', model:'500 cards total, 50-employee count', img:IMG+'MRX35-50-X-10-1.jpg', price:135, list:null, brand:'Acroprint',
    short:'Time cards for the MRX-35 series, 50 cards per pack, 10 packs per box.', bullets:['50 cards per pack × 10 packs','50-employee count'],
    compat:['MRX-35'],
    desc:'Genuine replacement cards sized for the MRX-35 — keep a fresh stock to avoid payroll downtime.' },
  { id:'MJR099', cat:'ribbons', name:'MJR Time Cards 0-99 (Box of 2000)', model:'Numbered 0-99, 2000 per box', img:IMG+'MJR099-1.jpg', price:155, list:null, brand:'Amano',
    short:'Time cards numbered 0-99 for the MJR series, 2000 per box.', bullets:['Numbered 0–99','2000 cards per box','7.375" × 3.25"'],
    compat:['MJR-7000','MJR-8000'],
    desc:'Genuine Amano MJR cards (0–99 employee count) sized 7.375" × 3.25" — a perfect fit for crisp, reliable punches.' },
  { id:'MJR0249', cat:'ribbons', name:'MJR Time Cards 0-249 (Box of 2000)', model:'Numbered 0-249, 2000 per box', img:IMG+'MJR0249-1.jpg', price:155, list:null, brand:'Amano',
    short:'Time cards numbered 0-249 for the MJR-8000 series, 2000 per box.', bullets:['Numbered 0–249','2000 cards per box','7.375" × 3.25"'],
    compat:['MJR-8000'],
    desc:'Higher-count Amano MJR-8000 cards (0–249) for larger workforces — same trusted fit and print quality.' },
  { id:'MRX351000', cat:'ribbons', name:'MRX-35 Time Cards (Box of 1000)', model:'1000 cards, 50-employee count', img:IMG+'MRX351000-1.jpg', price:198, list:null, brand:'Acroprint',
    short:'Time cards for the MRX-35 series, 1000 cards per box.', bullets:['1000 cards per box','50-employee count'],
    compat:['MRX-35'],
    desc:'A bulk box of genuine MRX-35 cards for high-volume environments that want to keep timekeeping running flawlessly.' },
];

/* helpers */
function fmt(n){ return '$' + Number(n).toLocaleString('en-US'); }
function getCat(id){ return CATEGORIES.find(c=>c.id===id); }
function getProduct(id){ return PRODUCTS.find(p=>p.id===id); }
function productsIn(catId){ return PRODUCTS.filter(p=>p.cat===catId); }
function searchProducts(q){
  q=(q||'').trim().toLowerCase(); if(!q) return [];
  const terms=q.split(/\s+/);
  return PRODUCTS.map(p=>{
    const hay=[p.name,p.model,p.brand,p.sub,getCat(p.cat)&&getCat(p.cat).name,(p.compat||[]).join(' ')].join(' ').toLowerCase();
    let score=0; terms.forEach(t=>{ if(hay.includes(t)) score++; if((p.name||'').toLowerCase().includes(t)) score++; });
    return {p,score};
  }).filter(x=>x.score>0).sort((a,b)=>b.score-a.score).map(x=>x.p);
}
