/* Time Clocks Unlimited — catalog data (real products, models, specs & pricing from timeclocksunltd.com) */
const IMG = 'assets/products/';

const CATEGORIES = [
  {
    id: 'netbell-pa',
    name: 'NetBell IP Public Address',
    short: 'IP Paging & PA Systems',
    tagline: 'Mass communication over your existing network',
    blurb: 'Connect every speaker across multiple buildings with a single network cable. Daily announcements, scheduled break bells, fire drills and OSHA-compliant emergency alerts — all managed from a simple desktop app or web browser.',
    icon: 'speaker',
    color: '#2563eb',
    benefits: [
      { t: 'Reduced Wiring Costs', d: 'Leverage your existing network — minimize expensive cabling and labor.' },
      { t: 'Simple DIY Installation', d: 'Install it yourself with just a screwdriver. Set up in minutes, no contractors.' },
      { t: 'Scalable for Growth', d: 'Start small and add more speakers anytime — no rewiring the whole facility.' },
      { t: 'Web-Based Scheduler', d: 'Program bell schedules from any browser with custom tones and messages.' },
      { t: 'VoIP Compatible', d: 'Integrate with your VoIP phone system for unified facility communications.' },
      { t: 'Seamless Integration', d: 'Tie into fire/security systems via digital inputs or RESTful API for instant emergency messages.' }
    ]
  },
  {
    id: 'break-bells',
    name: 'Break Bells & Buzzers',
    short: 'School, Office & Factory',
    tagline: 'Web-scheduled bell & buzzer systems',
    blurb: 'Set up a facility-wide break bell system in minutes with our network-enabled LINORTEK NetBell solution. Schedule break-time alerts from any web browser — ready-to-deploy or budget-friendly DIY — for schools, warehouses and factories.',
    icon: 'bell',
    color: '#f26a1b',
    subs: ['Web-Based / TCP-IP Systems', 'Wired Timer Switches']
  },
  {
    id: 'software',
    name: 'Time & Attendance',
    short: 'Biometric Clocks & Software',
    tagline: 'Facial recognition, fingerprint & cloud software',
    blurb: 'Touch-free facial-recognition and fingerprint terminals that stop "buddy punching" and flow straight into payroll. Cloud time management with PTO tracking, mobile app and offline mode — plus uAttend and Qqest software lines.',
    icon: 'face',
    color: '#0a1c2e',
    subs: ['uAttend Software', 'Qqest Software']
  },
  {
    id: 'time-clocks',
    name: 'Time Clocks',
    short: 'Amano Punch & Electronic',
    tagline: 'Proven Amano time recorders',
    blurb: 'Reliable Amano electronic and punch-card time recorders — the workhorses of timekeeping. Authorized dealer; we service what we sell.',
    icon: 'clock',
    color: '#0891b2',
    subs: ['Amano Time Clocks']
  },
  {
    id: 'date-stamps',
    name: 'Date & Numbering Stamps',
    short: 'Widmer Stamps',
    tagline: 'Authorized Widmer dealer',
    blurb: 'A complete line of Widmer date stamps, time stamps, check signers and embossers for document control in mailrooms, banks and validation centers. We service what we sell — call us for any model.',
    icon: 'stamp',
    color: '#7c3aed',
    subs: ['Widmer Date Stamps']
  },
  {
    id: 'ribbons',
    name: 'Ribbons, Cards & Supplies',
    short: 'Genuine Supplies',
    tagline: 'Keep your clocks running clean',
    blurb: 'Genuine replacement ribbons and time cards engineered for sharp, smudge-free imprints. Check the compatibility list on each item to match your exact clock model.',
    icon: 'supplies',
    color: '#16a34a'
  }
];

/* Each product: id (=image basename), cat, sub, name, model (subtitle line on the real site),
   img, price, list (was-price or null), brand, short (card blurb), bullets[], specs{}, compat[], desc (long) */
const PRODUCTS = [
  /* ---------- NetBell IP Public Address ---------- */
  { id:'01-910-00057', cat:'netbell-pa', name:'NetBell Warehouse / Factory Paging System', model:'Facility-wide IP paging & break-time system', img:IMG+'01-910-00057-1.jpg', price:2566, list:null, brand:'Linortek',
    short:'Everything needed for factory/warehouse mass notification — live announcements, pre-recorded messages, fire drills and break-bell scheduling.',
    bullets:['Web-based control of up to 500 programmable events','Extra-loud hardware cuts through industrial noise','Plug-and-play on your existing network, mounting hardware included','Custom or recorded tones; NTP automatic time sync'],
    desc:'Streamline daily operations across large floor plans. This all-in-one IP paging system automates every work bell and break buzzer with synchronized audio cues for lunch and shift changes — ideal for manufacturing plants, distribution centers, bakeries and textile mills.' },
  { id:'01-910-00058', cat:'netbell-pa', name:'School IP Paging Bell System', model:'Campus-wide bells, paging & emergency alerts', img:IMG+'01-910-00058-1.jpg', price:2566, list:null, brand:'Linortek',
    short:'Connect every speaker through your existing network — automated bell scheduling, campus-wide paging and emergency alerts for schools of any size.',
    bullets:['No expensive contractors or new wiring','Automated class-change & assembly bells','Live and pre-recorded campus announcements','Simple to install, affordable to own'],
    desc:'Transform your school’s communication with a complete IP audio solution: daily bells, all-call paging and critical emergency announcements, all from one web interface.' },
  { id:'01-910-00146', cat:'netbell-pa', name:'Warehouse & Factory Paging with VoIP', model:'VoIP phone integration + automated bells', img:IMG+'01-910-00146-1.jpg', price:2890, list:null, brand:'Linortek',
    short:'Make announcements directly from any desk phone while automating daily break bells, shift changes and emergency alerts.',
    bullets:['VoIP phone-system integration','Live paging from any handset','Automated break & shift signaling','Emergency notification ready'],
    desc:'Professional industrial communication with VoIP integration — perfect for facilities that want one simple system for mass communication and emergency notification.' },
  { id:'01-910-00137', cat:'netbell-pa', name:'NetBell Emergency Alert & Safety Paging', model:'OSHA-compliant emergency notification', img:IMG+'01-910-00137-1.jpg', price:3051, list:null, brand:'Linortek',
    short:'IP-based emergency system with instant alerts, pre-recorded messages, live announcements and one-button activation — 10,000 sq ft coverage per speaker.',
    bullets:['One-button instant emergency activation','Real-time voice, pre-recorded or automated triggers','10,000 sq ft coverage per speaker','OSHA-compliant employee alarm; deploys in hours'],
    desc:'Deliver critical information through live voice, pre-recorded messages or automated triggers from connected systems — built for manufacturing facilities, distribution centers and industrial complexes requiring immediate emergency communication.' },

  /* ---------- Break Bells & Buzzers (Web-Based / TCP-IP — Linortek) ---------- */
  { id:'01-910-00014', cat:'break-bells', sub:'Web-Based / TCP-IP Systems', name:'NetBell-2 TCP/IP Web-Based Bell Controller', model:'Controller only — up to 500 event schedules', img:IMG+'01-910-00014-1.jpg', price:425, list:468, brand:'Linortek',
    short:'The network "brains" of a school/factory bell system. Add your own bells or buzzers; schedule up to 500 events from any browser.',
    bullets:['Up to 500 programmable event schedules','No dedicated PC or extra software required','Schedule from any computer on your network'],
    desc:'A compact, self-contained network bell controller. Connect it to your existing bells or buzzers and program your entire schedule from a simple web browser.' },
  { id:'01-910-00025', cat:'break-bells', sub:'Web-Based / TCP-IP Systems', name:'NetBell-2 with 1 Bell', model:'Netbell-2-1Bel — controller + one 6" alarm bell', img:IMG+'01-910-00025-1.jpg', price:699, list:763, brand:'Linortek',
    short:'All-in-one kit: the versatile NetBell-2 controller plus a high-quality 6" work bell — a fully operational break-bell system out of the box.',
    bullets:['Up to 500 programmable events, each its own duration','No extra software or designated computer','Add a 2nd bell or a buzzer later as you grow','Manage break & shift times from any PC'],
    desc:'One of our most popular break-time solutions. Best for small-to-medium workshops, schools and warehouses needing a reliable, network-controlled schedule — with the future-proof benefit of expanding to a second device on the same controller.',
    specs:{ 'Event schedules':'Up to 500', 'Bell':'6" alarm bell included', 'Control':'Web browser, any networked PC', 'Expandable':'Add 2nd bell / buzzer' } },
  { id:'01-910-00027', cat:'break-bells', sub:'Web-Based / TCP-IP Systems', name:'NetBell-2 with 2 Bells', model:'Netbell-2-2Bel — controller + two 6" bells', img:IMG+'01-910-00027-1.jpg', price:985, list:1058, brand:'Linortek',
    short:'The web-based NetBell-2 controller with two loud 6" signal bells — perfect for noisier environments where audible alerts are critical.',
    bullets:['Two high-quality signal bells included','Schedule shift changes, breaks or class periods from a browser','Scale up by adding more bells or speakers','Functions as part of a modern IP PA system'],
    desc:'Connects to your existing network and delivers complete control from a web browser — no special software to install. Ideal for larger or louder facilities.' },
  { id:'01-910-00026', cat:'break-bells', sub:'Web-Based / TCP-IP Systems', name:'NetBell-2-1Buzzer Network Buzzer System', model:'Netbell-2-1PBuz — one 4" extra-loud buzzer', img:IMG+'01-910-00026-1.jpg', price:780, list:873, brand:'Linortek',
    short:'Network bell controller with one 4" extra-loud buzzer for industrial factory & warehouse break-time alerts.',
    bullets:['One 4" extra-loud industrial buzzer','Web-based scheduling software','Works with your existing time-clock software & network'],
    desc:'An Ethernet-enabled buzzer system that eliminates manual oversight — accurate signaling for shifts, meetings and emergencies, managed from any computer on your network.' },
  { id:'01-910-00028', cat:'break-bells', sub:'Web-Based / TCP-IP Systems', name:'NetBell-2-2Buzzer Network Buzzer System', model:'Netbell-2-2Buzzer — two 4" extra-loud buzzers', img:IMG+'01-910-00028-1.jpg', price:1140, list:1278, brand:'Linortek',
    short:'Two 4" extra-loud buzzers on one web-managed controller for maximum coverage in noisy industrial spaces.',
    bullets:['Two loud, high-quality buzzers included','Simple web interface, no PC software','Integrates with existing infrastructure'],
    desc:'Dependable, consistent scheduling for shifts, meetings and emergencies — built for large factory and warehouse floor plans.' },
  { id:'01-910-00119', cat:'break-bells', sub:'Web-Based / TCP-IP Systems', name:'NetBell-4-4Buz Network Buzzer System', model:'Four built-in buzzers + four contact closures', img:IMG+'01-910-00119-1.jpg', price:2089, list:2332, brand:'Linortek',
    short:'Run four distinct schedules from one device — used by large school districts, hospitals and expansive factories.',
    bullets:['Four independent zones / schedules','Automatic NTP time synchronization','Power of four devices in one compact enclosure','No complex internal wiring'],
    desc:'An advanced programmable bell system for multi-zone environments that demand strict time adherence — synchronized break-time signaling across departments or buildings.' },
  { id:'01-910-00035', cat:'break-bells', sub:'Web-Based / TCP-IP Systems', name:'NETBELL-4K Bell Controller Kit', model:'NEMA-rated, four relay outputs', img:IMG+'01-910-00035-1.jpg', price:641, list:712, brand:'Linortek',
    short:'Industrial NEMA-rated controller with four relay outputs to independently control up to four bells or signaling devices.',
    bullets:['Four relay outputs — up to four devices/zones','Up to 500 unique event schedules','Digital input for manual emergency ringing','Manage multiple units from a single interface'],
    desc:'Housed in a durable NEMA-rated enclosure for factories and warehouses. One of the most flexible break-time solutions available — program every zone from a browser with no software to install.' },
  { id:'01-910-00072', cat:'break-bells', sub:'Web-Based / TCP-IP Systems', name:'NetBell-KB Network Break Buzzer (Two-Zone)', model:'Netbell-KB-E2M — dual extra-loud outputs', img:IMG+'01-910-00072-1.jpg', price:1475, list:1553, brand:'Linortek',
    short:'Two-zone automated alerting for areas needing sharp, extra-loud signals — e.g. a warehouse floor and an assembly line.',
    bullets:['Dual outputs for two physically-separated zones','Automatic NTP time sync','Stagger lunches or shift changes by zone','Managed entirely via web interface'],
    desc:'A centralized break-bell system for industrial settings requiring high-decibel signals heard across different operational sections — unparalleled flexibility coordinating facility-wide timing.' },
  { id:'_01-910-00005', cat:'break-bells', sub:'Web-Based / TCP-IP Systems', name:'NetBell-K-C Break Bell & Clock System', model:'All-in-one bell + synchronized digital clock', img:IMG+'_01-910-00005-1.jpg', price:1250, list:1339, brand:'Linortek',
    short:'Network-based bell system with an included digital clock for a clear, unified time reference across your whole team.',
    bullets:['Up to 500 programmable event schedules','Built-in real-time clock, NTP + automatic DST/leap-year','BellScheduler desk app manages devices in multiple buildings','No wiring or control systems needed'],
    desc:'Completely automates time-based alerts for manufacturing plants, warehouses, distribution centers and schools. The included digital clock keeps everyone on the same page; manage multiple NetBell devices from one interface without going through the firewall.',
    specs:{ 'Event schedules':'Up to 500', 'Clock':'Built-in, NTP + auto DST', 'App':'BellScheduler desk app', 'Multi-building':'Yes' } },
  { id:'01-910-00059', cat:'break-bells', sub:'Web-Based / TCP-IP Systems', name:'NetBell-NTG Tone & Message Generator', model:'For schools / commercial PA systems', img:IMG+'01-910-00059-1.jpg', price:748, list:831, brand:'Linortek',
    short:'Turns your existing speakers into a web-based programmable bell system — generates digital tones and pre-recorded voice messages instead of physical bells.',
    bullets:['40 standard tones/messages; record custom up to 120 hrs','16 tones selectable by schedule or digital input','Plays over your current PA / paging speakers','BellScheduler app for easy management'],
    desc:'An all-in-one upgrade if you already have speakers installed. Bridges a basic break-bell system and a full IP public address system — schedule different tones for different events or play voice messages for security alerts and shift changes.' },
  { id:'01-910-00075', cat:'break-bells', sub:'Web-Based / TCP-IP Systems', name:'NetBell-NTG-C2 Paging System (2 Speakers)', model:'TCP/IP PA paging with live voice', img:IMG+'01-910-00075-1.jpg', price:1882, list:2091, brand:'Linortek',
    short:'Complete two-speaker IP public address system handling both scheduled alerts and live voice paging.',
    bullets:['Two high-quality speakers included','Integrated microphone input for live announcements','Schedule tones, messages or background music','NTP automatic time synchronization'],
    desc:'Combines a break-bell system with full paging capabilities — broadcast custom tones, messages and music, or make immediate live emergency announcements over excellent dual-speaker coverage.' },
  { id:'01-910-00013', cat:'break-bells', sub:'Web-Based / TCP-IP Systems', name:'NetBell-K TCP/IP Break Bell System', model:'Web-based all-in-one, up to 500 events', img:IMG+'01-910-00013-1.jpg', price:755, list:839, brand:'Linortek',
    short:'A self-contained, web-based all-in-one school/factory break-bell system with up to 500 event schedules.',
    bullets:['Up to 500 event schedules','All-in-one, self-contained','Web-based management'],
    desc:'A dependable, network-controlled break-bell system that runs independently of your main computer for superior reliability.' },
  { id:'01-910-00045', cat:'break-bells', sub:'Web-Based / TCP-IP Systems', name:'NetBell-K-E1 Web-Based Break Bell System', model:'All-in-one with one external bell', img:IMG+'01-910-00045-1.jpg', price:1050, list:1154, brand:'Linortek',
    short:'Loud all-in-one electric school/factory/warehouse break-alarm system with one external bell and programmable web-based timer software.',
    bullets:['One external bell included','Programmable web-based bell timer','Self-contained electronic controller'],
    desc:'A loud, automatic, programmable break-bell system for schools, factories and warehouses — web-based control with no PC software to install.' },
  { id:'01-910-00049', cat:'break-bells', sub:'Web-Based / TCP-IP Systems', name:'NetBell-K-E2M Web-Based Break Bell System', model:'Two external bells + manual push-button', img:IMG+'01-910-00049-1.jpg', price:1350, list:1498, brand:'Linortek',
    short:'All-in-one loud break-bell system with two external bells and a push-button switch to ring the bell manually for emergencies.',
    bullets:['Two external bells included','Manual push-button for emergency ring','Programmable web-based timer software'],
    desc:'A loud, automatic, programmable break-bell system with two bells for wider coverage plus a manual override for emergencies.' },
  { id:'01-910-00029', cat:'break-bells', sub:'Web-Based / TCP-IP Systems', name:'NETBELL-KL High-Volume Break Bell System', model:'90 dBA @ 30 ft for noisy/large areas', img:IMG+'01-910-00029-1.jpg', price:910, list:1011, brand:'Linortek',
    short:'Self-contained web-based break-bell system with a high-volume 90 dBA @ 30′ bell for noisier, larger industrial working areas.',
    bullets:['High-output 90 dBA @ 30′ bell','Fully automated programmable schedule','No extra software; runs independently of your PC','Instant schedule changes from any networked computer'],
    desc:'Engineered for large, noisy industrial spaces — an incredibly loud bell guaranteed to cut through industrial noise, in a self-contained, maintenance-free design built for harsh environments.' },

  /* ---------- Time & Attendance — Biometric Clocks ---------- */
  { id:'JR2000', cat:'software', name:'JR2000 Time Clock', model:'Touch tablet with biometric finger scanner', img:IMG+'JR2000-1.png', price:179, list:null, brand:'Velocity',
    short:'Affordable touch-tablet time clock with a biometric fingerprint scanner — a simple, accurate entry point to digital timekeeping.',
    bullets:['Biometric fingerprint punch','Touch-tablet interface','Cloud-ready time tracking'],
    desc:'A budget-friendly biometric terminal that brings accurate, tamper-resistant punching to small teams.' },
  { id:'DR2000', cat:'software', name:'DR2000 Time Clock', model:'Touch-free voice control & facial recognition', img:IMG+'DR2000-1.jpg', price:299, list:null, brand:'Velocity',
    short:'Touch-free facial recognition (even with masks) plus voice control — eliminates "buddy punching" and keeps surfaces hygienic.',
    bullets:['Facial recognition, voice, RFID badge & PIN','Recognizes faces even with masks on','Offline mode stores punches during outages','Dedicated mobile app; cloud software, payroll export'],
    desc:'A cutting-edge, cloud-based terminal for the best workforce management. View time cards, track PTO accruals and export directly to major payroll systems — secure, touch-free and uninterrupted timekeeping.',
    specs:{ 'Punch methods':'Face, voice, RFID, PIN', 'Masks':'Recognized', 'Connectivity':'Wi-Fi / LAN', 'Offline':'Yes, stores punches', 'App':'Mobile app included' } },
  { id:'DR2500', cat:'software', name:'DR2500 Time Clock', model:'Facial recognition + temperature reader', img:IMG+'DR2500-1.jpg', price:399, list:null, brand:'Velocity',
    short:'All the DR2000 touch-free facial & voice recognition, plus an integrated temperature reader for added workplace safety.',
    bullets:['Touch-free facial & voice recognition','Integrated temperature reading','Integrates into existing payroll/time software','Wi-Fi / LAN real-time data'],
    desc:'Adds advanced facial recognition and temperature screening as a front-end to your existing best-in-class time system — automating the most error-prone part of timekeeping: the punch itself.' },
  { id:'V800', cat:'software', name:'Velocity 800 Time Clock', model:'Fingerprint & on-demand technology', img:IMG+'V800-1.jpg', price:1290, list:null, brand:'Velocity',
    short:'Professional fingerprint time clock with on-demand technology for accurate, high-volume employee time tracking.',
    bullets:['Biometric fingerprint','On-demand technology','Built for everyday workforce use'],
    desc:'A robust fingerprint terminal from the Velocity line, designed for reliable daily punching across your workforce.' },
  { id:'V850', cat:'software', name:'Velocity 850 Time Clock', model:'Fingerprint + Dept Transfer, Job Costing, Tips', img:IMG+'V850-1.jpg', price:1790, list:null, brand:'Velocity',
    short:'Velocity 850 adds department transfer, job costing and tips keys — ideal for businesses that bill by job or track tipped labor.',
    bullets:['Fingerprint + on-demand technology','Department transfer & job costing','Tips keys for hospitality'],
    desc:'A feature-rich biometric terminal for operations that need to allocate labor to departments or jobs and capture tips at the clock.' },
  { id:'V850R', cat:'software', name:'Velocity 850 Rugged', model:'Worksite-ready: Ethernet, POE or Wireless', img:IMG+'V850R-1.jpg', price:2290, list:null, brand:'Velocity',
    short:'A ruggedized Velocity 850 designed for worksites, with three connectivity options — Ethernet, POE or Wireless.',
    bullets:['Rugged housing for job sites','Dept transfer, job costing, tips keys','Three options: Ethernet, POE, Wireless'],
    desc:'Built to take on demanding worksites while keeping all the job-costing power of the Velocity 850 — choose the connectivity that fits your environment.' },

  /* ---------- Time Clocks — Amano ---------- */
  { id:'CP-5000', cat:'time-clocks', sub:'Amano Time Clocks', name:'Amano CP-5000 Electronic Time Recorder', model:'Electronic time recorder', img:IMG+'CP-5000-1.jpg', price:950, list:1150, brand:'Amano',
    short:'A dependable Amano electronic time recorder for straightforward, accurate punch-card timekeeping.',
    bullets:['Amano reliability','Electronic time recording','Authorized dealer — we service what we sell'],
    desc:'A proven Amano workhorse for businesses that want simple, accurate, low-maintenance time recording.' },
  { id:'MJR-PLUS', cat:'time-clocks', sub:'Amano Time Clocks', name:'Amano MJR-PLUS', model:'Calculating time recorder', img:IMG+'MJR-PLUS-1.jpg', price:499, list:null, brand:'Amano',
    short:'Affordable Amano MJR-series calculating time recorder for small and growing teams.',
    bullets:['Amano MJR series','Calculating time recorder','Great value'],
    desc:'An economical entry into Amano’s trusted MJR line — reliable punch-card timekeeping that totals hours for you.' },
  { id:'MJR-7000-1167', cat:'time-clocks', sub:'Amano Time Clocks', name:'Amano MJR-7000', model:'Calculating time recorder', img:IMG+'MJR-7000-1167-1.png', price:1250, list:1475, brand:'Amano',
    short:'The popular Amano MJR-7000 calculating time recorder — accurate totals and dependable daily operation.',
    bullets:['Amano MJR-7000','Automatic hour calculation','Uses MJR 0-99 time cards & black ribbon'],
    desc:'A higher-capacity Amano calculating recorder for busier workplaces — pair it with MJR time cards and ribbons (in our Supplies category).' },
  { id:'PIX-200-0400', cat:'time-clocks', sub:'Amano Time Clocks', name:'Amano PIX-200 Time Clock / Date Stamp', model:'Electronic time clock & date stamp', img:IMG+'PIX-200-0400-1.jpg', price:395, list:455, brand:'Amano',
    short:'Versatile Amano PIX-200 that works as both an electronic time clock and a document date stamp.',
    bullets:['Dual purpose: time clock + date stamp','Uses C3000 time cards & PIX10 ribbons','Compact and reliable'],
    desc:'A flexible Amano unit for offices that need both employee timekeeping and document time/date stamping in one device.' },
  { id:'PIX200-with-signal-kit', cat:'time-clocks', sub:'Amano Time Clocks', name:'Amano PIX-200 with Timer Signal Kit', model:'PIX-200 bundled with bell/signal kit', img:IMG+'PIX200-with-signal-kit-1.jpg', price:499, list:null, brand:'Amano',
    short:'The PIX-200 time clock / date stamp bundled with a timer signal kit to ring a bell or buzzer on schedule.',
    bullets:['PIX-200 time clock + date stamp','Includes timer signal kit','Drives a bell/buzzer on schedule'],
    desc:'Adds simple scheduled-signal capability to the dependable PIX-200 — a tidy combo for shops that want timekeeping and a break bell from one device.' },

  /* ---------- Date & Numbering Stamps — Widmer ---------- */
  { id:'T3', cat:'date-stamps', sub:'Widmer Date Stamps', name:'Widmer T-3 Electronic Date & Time Stamp', model:'Widmer T3 electronic time stamp', img:IMG+'T3-1.jpg', price:960, list:null, brand:'Widmer',
    short:'Precision Widmer T-3 electronic date & time stamp for clean, indisputable document time-stamping.',
    bullets:['Electronic date & time imprint','Authorized Widmer dealer','We service what we sell'],
    desc:'A reliable workhorse for mailrooms and offices that need accurate, legible date/time validation on documents.' },
  { id:'T3-LED', cat:'date-stamps', sub:'Widmer Date Stamps', name:'Widmer T3-LED Electronic Time Stamp', model:'T-3 with LED display', img:IMG+'T3-LED-1.jpg', price:1010, list:null, brand:'Widmer',
    short:'The Widmer T-3 with a clear LED display for easy reading and confident document stamping.',
    bullets:['Bright LED display','Electronic time stamp','Authorized Widmer dealer'],
    desc:'All the accuracy of the Widmer T-3 line with an added LED display for fast, error-free operation.' },
  { id:'776', cat:'date-stamps', sub:'Widmer Date Stamps', name:'Widmer 776 Dual-Head Date Stamp', model:'Stamps top & bottom of a document simultaneously', img:IMG+'776-1.jpg', price:1321, list:null, brand:'Widmer',
    short:'Heavy-duty dual-head date stamp for high-volume document validation — imprints the top and bottom of a document at once.',
    bullets:['Dual-head: stamps two locations simultaneously','Industrial-grade, high-volume','Ideal for mailrooms, banks, validation centers'],
    desc:'For high-volume environments needing instant, indisputable proof of time and date — processing checks, parking stubs and legal forms. One of the most important accessories for organizations validating paper records.' },

  /* ---------- Ribbons, Cards & Supplies ---------- */
  { id:'MJR-Ribbon', cat:'ribbons', name:'MJR Black Ribbon (Pack of 2)', model:'Single-color black ribbon', img:IMG+'MJR-Ribbon-1.jpg', price:48, list:null, brand:'Amano',
    short:'Genuine black ribbon, sold in a pack of 2.', bullets:['Pack of 2','Sharp, smudge-free imprints'],
    compat:['MJR-7000','MJR-8000'],
    desc:'Keep your Amano MJR recorder printing crisply. Stocking spares prevents payroll downtime and keeps timestamps legible for audits.' },
  { id:'PIX10', cat:'ribbons', name:'PIX10 Black Ribbons (Pack of 3)', model:'Black ribbon cartridges', img:IMG+'PIX10-1.jpg', price:54, list:null, brand:'Amano',
    short:'Black ribbon cartridges, sold in a pack of 3.', bullets:['Pack of 3','Premium nylon, resists drying'],
    compat:['TCX series: 11/21/22/45/85/90','PIX series: 10/15/21/25/55/75/95/200/3000x','BX-6000'],
    desc:'Wide-compatibility ribbon for many TCX and PIX series clocks — fresh ink ensures legible punches and protects you during labor-law audits.' },
  { id:'AR175', cat:'ribbons', name:'175 Black Ribbon (Pack of 3)', model:'AR175 black ribbon', img:IMG+'AR175-1.jpg', price:54, list:null, brand:'Acroprint',
    short:'Premium replacement cartridge for sharp, smudge-free imprints, pack of 3.', bullets:['Pack of 3','Durable nylon construction'],
    compat:['MRX-35','Acroprint 175','MP550 Date Stamp','ES700 / ES900','and many more'],
    desc:'A premium black ribbon engineered for legible imprints on every time card — durable nylon that resists drying out in high-traffic industrial environments.' },
  { id:'5650-Purple', cat:'ribbons', name:'5650 Purple Ribbons (Box of 6)', model:'Purple date-stamp ribbon', img:IMG+'5650-Purple-1.jpg', price:75, list:null, brand:'Amano',
    short:'Genuine purple ribbons for date-stamp machines, box of 6.', bullets:['Box of 6','Consistent, dark purple saturation'],
    compat:['5650 time clock'],
    desc:'Keep mechanical time clocks running smoothly with crisp, legible purple punches — a low-cost way to prevent payroll errors from faded cards.' },
  { id:'C3000', cat:'ribbons', name:'C3000 Time Cards (Box of 1000)', model:'Time cards, 1000 per box', img:IMG+'C3000-1.jpg', price:75, list:null, brand:'Amano',
    short:'Genuine C3000 time cards, 1000 per box.', bullets:['1000 cards per box','Smudge-resistant, durable stock'],
    compat:['PIX-200'],
    desc:'A perfect fit for the PIX-200 — sturdy cards engineered to prevent smudging and resist wear for confident, accurate records.' },
  { id:'MRX35-50-X-10', cat:'ribbons', name:'MRX-35 Time Cards (50-pack, 10 packs/box)', model:'500 cards total, 50-employee count', img:IMG+'MRX35-50-X-10-1.jpg', price:135, list:null, brand:'Acroprint',
    short:'Time cards for the MRX-35 series, 50 cards per pack, 10 packs per box.', bullets:['50 cards per pack × 10 packs','50-employee count'],
    compat:['MRX-35'],
    desc:'Genuine replacement cards sized for the MRX-35 — keep a fresh stock to avoid payroll downtime.' },
  { id:'MJR099', cat:'ribbons', name:'MJR Time Cards 0-99 (Box of 2000)', model:'Numbered 0-99, 2000 per box', img:IMG+'MJR099-1.jpg', price:155, list:null, brand:'Amano',
    short:'Time cards numbered 0-99 for the MJR series, 2000 per box.', bullets:['Numbered 0–99','2000 cards per box','7.375" × 3.25"'],
    compat:['MJR-7000','MJR-8000'],
    desc:'Genuine Amano MJR cards (0–99 employee count) sized 7.375" × 3.25" — a perfect fit for crisp, reliable punches.' },
  { id:'MJR0249', cat:'ribbons', name:'MJR Time Cards 0-249 (Box of 2000)', model:'Numbered 0-249, 2000 per box', img:IMG+'MJR0249-1.jpg', price:155, list:null, brand:'Amano',
    short:'Time cards numbered 0-249 for the MJR-8000 series, 2000 per box.', bullets:['Numbered 0–249','2000 cards per box','7.375" × 3.25"'],
    compat:['MJR-8000'],
    desc:'Higher-count Amano MJR-8000 cards (0–249) for larger workforces — same trusted fit and print quality.' },
  { id:'MRX351000', cat:'ribbons', name:'MRX-35 Time Cards (Box of 1000)', model:'1000 cards, 50-employee count', img:IMG+'MRX351000-1.jpg', price:198, list:null, brand:'Acroprint',
    short:'Time cards for the MRX-35 series, 1000 cards per box.', bullets:['1000 cards per box','50-employee count'],
    compat:['MRX-35'],
    desc:'A bulk box of genuine MRX-35 cards for high-volume environments that want to keep timekeeping running flawlessly.' },
];

/* helpers */
function fmt(n){ return '$' + n.toLocaleString('en-US'); }
function getCat(id){ return CATEGORIES.find(c=>c.id===id); }
function getProduct(id){ return PRODUCTS.find(p=>p.id===id); }
function productsIn(catId){ return PRODUCTS.filter(p=>p.cat===catId); }
